### ISSUE TITLE
Auto Pricing Tool # Add the quantity for this existing data

### ISSUE THREAD

**Issue by Santhiblumaple** [daintree2016/Tools-related-Issues#3]
In the present data we need a extra column for Quantity.  If you provide that we will use fixed price alerts to work faster.

Thanks
Inturi Santhi Priya
![Screenshot 2024-09-23 122413](https://github.com/user-attachments/assets/96028de6-fda4-4f81-a925-fe90f47f3d61)
![Screenshot 2024-09-23 122536](https://github.com/user-attachments/assets/6bb47ec5-b1c3-430e-a9b0-4998a7a60d78)

**Comment by raj7032** [comment]
@Santhiblumaple 
Hi santhi vinturi, 
The issue thread you have created seems to be an off-topic, since auto pricing calculator only provides the recent US price price changes and calculates the sale, min, max, mrp accordingly. the quantity is a variable factor which the uploader needs to decide based on stock count.

Hope this helps, if your issue is not resolved yet please create a new thread and explain why you need this with more details including how it could reduce the manual effort and thereby we can decide the prominence in this topic or issue then will act accordingly.

Thanks
Rajkumar.
