### ISSUE TITLE
Need Program Tools for Doveberry

### ISSUE THREAD

**Issue by Amit-2468** [daintree2016/Tools-related-Issues#9]
Hi @daintree2016/it-services 

Required Program Tools for Doveberry, All Programs which we are currently using for Blumaple.

**Comment by raj7032** [comment]
Hey Amit, Thanks for reaching out. Could you pls explain what do you mean by **required new tools for doveberry.**
since the tools we provided are generalized program tools irrespective of the domains we support. If you really meant to say separate tools for Doveberry based on some use cases. elaborate and explain and why do you need them in detail by mentioning each tool name in a separate thread.

**Comment by Amit-2468** [comment]
Hi @daintree2016/it-services 

I had requested the development of the following programs for Doveberry:

1) Live Orders Program (Offline): To streamline and manage offline order processing.

2) New Launches Program: To facilitate and promote new product launches effectively.

3) Buy Box Program (Both Online & Offline): To optimize our buy box strategy across all platforms.

4) Simple Dot Com Program (Both Online & Offline): To enhance our online and offline presence and customer engagement.

5) Refunds Checker Program (Offline): To efficiently manage and track refunds in an offline environment.

These programs are essential for improving our operational efficiency. Please let me know if you need any additional information.

Thank you for your attention to this matter. I look forward to your prompt response.

Regards
Amit Tamboli
@daintree2016/operations

**Comment by raj7032** [comment]
Hi Amit,
Thanks for the details. Sure, I consider your request, surely we understand
the requirements of the listed tools and Our team will contact you shortly
for more details.
you can reach out to the IT members for any more updates belonging to this
thread.
--Rajkumar

**Comment by raj7032** [comment]
All required tools are provided to doveberry
